version: '3'
services:
      db:
         image: mysql:5.7
         container_name: mysql
         ports:
             - "3306:3006"
         env_file: env_file.txt
         volumes:
             - "/home/prathmesh/docker/04062021/compose/volume/check:/var/lib/mysql"
